// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var AwsAmplify = require("aws-amplify");
var AwsExportsJs = require("../aws-exports.js");

var awsConfig = AwsExportsJs.default;

AwsAmplify.default.configure(awsConfig);

var Configure = /* module */[
  /* awsConfig */awsConfig,
  /* configure : () */0
];

function configure(param) {
  return /* () */0;
}

exports.Configure = Configure;
exports.configure = configure;
/* awsConfig Not a pure module */
