// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var AwsAmplify = require("aws-amplify");

var currentAuthenticatedUser = AwsAmplify.Auth.currentAuthenticatedUser().then((function (res) {
        return Promise.resolve(res);
      }));

exports.currentAuthenticatedUser = currentAuthenticatedUser;
/* currentAuthenticatedUser Not a pure module */
