// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Js_option = require("bs-platform/lib/js/js_option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function errorToObj(err) {
  var match = Js_json.classify(err);
  var exit = 0;
  if (typeof match === "number") {
    exit = 1;
  } else {
    switch (match.tag | 0) {
      case 0 : 
          return /* Message */Block.__(0, [match[0]]);
      case 2 : 
          var obj = match[0];
          var l = List.map(Js_null_undefined.fromOption, List.map((function (param) {
                      return Js_option.andThen(Js_json.decodeString, param);
                    }), List.map((function (param) {
                          return Js_dict.get(obj, param);
                        }), /* :: */[
                        "code",
                        /* :: */[
                          "message",
                          /* :: */[
                            "name",
                            /* [] */0
                          ]
                        ]
                      ])));
          var match$1;
          if (l) {
            var match$2 = l[1];
            if (match$2) {
              var match$3 = match$2[1];
              match$1 = match$3 && !match$3[1] ? /* tuple */[
                  l[0],
                  match$2[0],
                  match$3[0]
                ] : /* tuple */[
                  null,
                  null,
                  null
                ];
            } else {
              match$1 = /* tuple */[
                null,
                null,
                null
              ];
            }
          } else {
            match$1 = /* tuple */[
              null,
              null,
              null
            ];
          }
          return /* Response */Block.__(1, [{
                      code: match$1[0],
                      message: match$1[1],
                      name: match$1[2]
                    }]);
      default:
        exit = 1;
    }
  }
  if (exit === 1) {
    var errMsg = Js_option.getWithDefault("", Caml_option.undefined_to_opt(JSON.stringify(err)));
    return /* Message */Block.__(0, ["An error occurred: " + errMsg]);
  }
  
}

exports.errorToObj = errorToObj;
/* No side effect */
