// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var UserMenu$ReactHooksTemplate = require("./UserMenu.bs.js");
var UserMenuWithHook$ReactHooksTemplate = require("./UserMenuWithHook.bs.js");

function Header(Props) {
  return React.createElement("header", undefined, React.createElement("div", {
                  className: "nav-container"
                }, React.createElement("a", {
                      className: "nav-link",
                      href: "#"
                    }, "Home"), React.createElement("a", {
                      className: "nav-link",
                      href: "#"
                    }, "Search"), React.createElement("a", {
                      className: "nav-link",
                      href: "#"
                    }, "Dashboard")), React.createElement("div", {
                  className: "user-menu"
                }, React.createElement(UserMenu$ReactHooksTemplate.make, { })), React.createElement("div", {
                  className: "user-menu"
                }, React.createElement(UserMenuWithHook$ReactHooksTemplate.make, { })));
}

var make = Header;

exports.make = make;
/* react Not a pure module */
