// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Root$ReactHooksTemplate = require("./Root.bs.js");

((require("../styles.css")));

ReactDOMRe.renderToElementWithId(React.createElement(Root$ReactHooksTemplate.make, { }), "root");

/*  Not a pure module */
