// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Page(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "A page"));
}

var make = Page;

exports.make = make;
/* react Not a pure module */
