// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Auth$ReactHooksTemplate = require("./aws/Auth.bs.js");
var Page$ReactHooksTemplate = require("./Page.bs.js");
var Header$ReactHooksTemplate = require("./Header.bs.js");
var UserProvider$ReactHooksTemplate = require("./UserProvider.bs.js");

function reducer(param, action) {
  if (action) {
    return /* record */[/* user : LoggedIn */[action[0]]];
  } else {
    return /* record */[/* user : Anonymous */0];
  }
}

function Root(Props) {
  var match = React.useReducer(reducer, /* record */[/* user : Anonymous */0]);
  React.useEffect((function () {
          console.log("userData", Auth$ReactHooksTemplate.currentAuthenticatedUser);
          return undefined;
        }), /* array */[]);
  return React.createElement(UserProvider$ReactHooksTemplate.make, UserProvider$ReactHooksTemplate.makeProps(/* tuple */[
                  match[0][/* user */0],
                  match[1]
                ], React.createElement(React.Fragment, undefined, React.createElement(Header$ReactHooksTemplate.make, { }), React.createElement("main", undefined, React.createElement(Page$ReactHooksTemplate.make, { }))), /* () */0));
}

var make = Root;

exports.reducer = reducer;
exports.make = make;
/* react Not a pure module */
