// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var UserContext$ReactHooksTemplate = require("./UserContext.bs.js");

function str(prim) {
  return prim;
}

function UserMenuWithHook(Props) {
  var match = UserContext$ReactHooksTemplate.useUser(/* () */0);
  var dispatch = match[1];
  var user = match[0];
  var match$1 = React.useState((function () {
          return "";
        }));
  var setUserName = match$1[1];
  var userName = match$1[0];
  if (user) {
    return React.createElement("div", {
                className: "user-form"
              }, React.createElement("span", {
                    className: "logged-in"
                  }, "Logged in as: ", React.createElement("b", undefined, user[0])), React.createElement("button", {
                    onClick: (function (param) {
                        return Curry._1(dispatch, /* UserLoggedOut */0);
                      })
                  }, "Log out"));
  } else {
    return React.createElement("form", {
                className: "user-form",
                onSubmit: (function (e) {
                    e.preventDefault();
                    return Curry._1(dispatch, /* UserLoggedIn */[userName]);
                  })
              }, React.createElement("input", {
                    className: "login-input",
                    placeholder: "User name",
                    value: userName,
                    onChange: (function (e) {
                        var value = e.target.value;
                        return Curry._1(setUserName, (function (param) {
                                      return value;
                                    }));
                      })
                  }), React.createElement("button", {
                    type: "submit"
                  }, "Log in"));
  }
}

var make = UserMenuWithHook;

exports.str = str;
exports.make = make;
/* react Not a pure module */
