// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var context = React.createContext(/* Anonymous */0);

function useUser(param) {
  return React.useContext(context);
}

function initValue_001(param) {
  return /* () */0;
}

var initValue = /* tuple */[
  /* Anonymous */0,
  initValue_001
];

exports.context = context;
exports.useUser = useUser;
exports.initValue = initValue;
/* context Not a pure module */
