// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var AwsAuth$ReactHooksTemplate = require("./aws/AwsAuth.bs.js");
var UserContext$ReactHooksTemplate = require("./UserContext.bs.js");

function str(prim) {
  return prim;
}

function UserMenuAws(Props) {
  var match = UserContext$ReactHooksTemplate.useUser(/* () */0);
  var dispatch = match[1];
  var user = match[0];
  var match$1 = React.useState((function () {
          return "";
        }));
  var setUserName = match$1[1];
  var userName = match$1[0];
  var match$2 = React.useState((function () {
          return "";
        }));
  var setPassword = match$2[1];
  var password = match$2[0];
  if (user) {
    return React.createElement("div", {
                className: "user-form"
              }, React.createElement("span", {
                    className: "logged-in"
                  }, "Logged in as: ", React.createElement("b", undefined, user[0])), React.createElement("button", {
                    onClick: (function (e) {
                        e.preventDefault();
                        AwsAuth$ReactHooksTemplate.signOut(/* () */0);
                        return Curry._1(dispatch, /* UserLoggedIn */[userName]);
                      })
                  }, "Log out"));
  } else {
    return React.createElement("form", {
                className: "user-form",
                onSubmit: (function (e) {
                    e.preventDefault();
                    console.log(userName, password);
                    AwsAuth$ReactHooksTemplate.signIn(userName, password).then((function (result) {
                              console.log("successfully signed in", result);
                              Curry._1(dispatch, /* UserLoggedIn */[userName]);
                              return Promise.resolve(/* () */0);
                            })).catch((function (err) {
                            console.log(err);
                            var errMsg = "error signing up..." + String(err);
                            console.log(errMsg);
                            return Promise.resolve(/* () */0);
                          }));
                    return /* () */0;
                  })
              }, React.createElement("input", {
                    className: "login-input",
                    placeholder: "User name",
                    value: userName,
                    onChange: (function (e) {
                        var value = e.target.value;
                        return Curry._1(setUserName, (function (param) {
                                      return value;
                                    }));
                      })
                  }), React.createElement("input", {
                    className: "login-input",
                    placeholder: "Password",
                    value: password,
                    onChange: (function (e) {
                        var value = e.target.value;
                        return Curry._1(setPassword, (function (param) {
                                      return value;
                                    }));
                      })
                  }), React.createElement("button", {
                    type: "submit"
                  }, "Log in"));
  }
}

var make = UserMenuAws;

exports.str = str;
exports.make = make;
/* react Not a pure module */
