// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var context = React.createContext(/* Anonymous */0);

function useUser(param) {
  return React.useContext(context);
}

exports.context = context;
exports.useUser = useUser;
/* context Not a pure module */
