// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function initValue_001(param) {
  return /* () */0;
}

var initValue = /* tuple */[
  /* Anonymous */0,
  initValue_001
];

var context = React.createContext(initValue);

function useUser(param) {
  return React.useContext(context);
}

exports.initValue = initValue;
exports.context = context;
exports.useUser = useUser;
/* context Not a pure module */
