// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var UserContext$ReactHooksTemplate = require("./UserContext.bs.js");

var make = UserContext$ReactHooksTemplate.context.Provider;

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

exports.make = make;
exports.makeProps = makeProps;
/* make Not a pure module */
